//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3d_render_secure_login_password_illustration_107791_16640 {
            get {
                object obj = ResourceManager.GetObject("3d-render-secure-login-password-illustration_107791-16640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _458_REpWIE1BUiAwODktMDU {
            get {
                object obj = ResourceManager.GetObject("458_REpWIE1BUiAwODktMDU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _458_REpWIE1BUiAwODktMDU1 {
            get {
                object obj = ResourceManager.GetObject("458_REpWIE1BUiAwODktMDU1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _458_REpWIE1BUiAwODktMzA {
            get {
                object obj = ResourceManager.GetObject("458_REpWIE1BUiAwODktMzA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap air_conditioning_repair_instalation_service_repairman_installing_examining_repairing_conditioner_with_special_tools_equipment_isolated_vector_illustration_613284_1785 {
            get {
                object obj = ResourceManager.GetObject("air-conditioning-repair-instalation-service-repairman-installing-examining-repair" +
                        "ing-conditioner-with-special-tools-equipment-isolated-vector-illustration_613284" +
                        "-1785", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap automobile_production_line_using_robots_work_smart_factories_3d_illustration_1300x650 {
            get {
                object obj = ResourceManager.GetObject("automobile-production-line-using-robots-work-smart-factories-3d-illustration-1300" +
                        "x650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bendy_gears_icon {
            get {
                object obj = ResourceManager.GetObject("bendy-gears-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bendy_industrial_robotics {
            get {
                object obj = ResourceManager.GetObject("bendy-industrial-robotics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bendy_industrial_robotics1 {
            get {
                object obj = ResourceManager.GetObject("bendy-industrial-robotics1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black_man_carrying_wrench_112255_3897 {
            get {
                object obj = ResourceManager.GetObject("black-man-carrying-wrench_112255-3897", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boy_is_attracting_buyers_118167_4765 {
            get {
                object obj = ResourceManager.GetObject("boy-is-attracting-buyers_118167-4765", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boy_is_attracting_buyers_118167_47651 {
            get {
                object obj = ResourceManager.GetObject("boy-is-attracting-buyers_118167-47651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boy_is_attracting_buyers_118167_47652 {
            get {
                object obj = ResourceManager.GetObject("boy-is-attracting-buyers_118167-47652", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap building_construction_engineering_construction_workers_engineers_helmets_construction_site_with_cranes_vector_eps_10_532800_1396 {
            get {
                object obj = ResourceManager.GetObject("building-construction-engineering-construction-workers-engineers-helmets-construc" +
                        "tion-site-with-cranes-vector-eps-10_532800-1396", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap building_construction_engineering_construction_workers_engineers_helmets_construction_site_with_cranes_vector_eps_10_532800_13961 {
            get {
                object obj = ResourceManager.GetObject("building-construction-engineering-construction-workers-engineers-helmets-construc" +
                        "tion-site-with-cranes-vector-eps-10_532800-13961", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_business_concept_with_purchase_contract_symbols_flat_vector_illustration_1284_76939 {
            get {
                object obj = ResourceManager.GetObject("business-business-concept-with-purchase-contract-symbols-flat-vector-illustration" +
                        "_1284-76939", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_business_concept_with_purchase_contract_symbols_flat_vector_illustration_1284_769391 {
            get {
                object obj = ResourceManager.GetObject("business-business-concept-with-purchase-contract-symbols-flat-vector-illustration" +
                        "_1284-769391", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_contract_agreement_website_template_flat_vector_illustration_605858_2601 {
            get {
                object obj = ResourceManager.GetObject("business-contract-agreement-website-template-flat-vector-illustration_605858-2601" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_deal_concept_background_23_2148104844 {
            get {
                object obj = ResourceManager.GetObject("business-deal-concept-background_23-2148104844", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_deal_concept_background_23_21481048441 {
            get {
                object obj = ResourceManager.GetObject("business-deal-concept-background_23-21481048441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_deal_concept_background_23_21481048442 {
            get {
                object obj = ResourceManager.GetObject("business-deal-concept-background_23-21481048442", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_handshake_deal_making_businessmen_shake_hands_vector_illustration_flat_design_131476_106 {
            get {
                object obj = ResourceManager.GetObject("business-handshake-deal-making-businessmen-shake-hands-vector-illustration-flat-d" +
                        "esign_131476-106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_logistics_abstract_concept_vector_illustration_smart_logistics_technologies_commercial_delivery_service_worldwide_business_transportation_global_product_shipment_abstract_metaphor_335657_1788 {
            get {
                object obj = ResourceManager.GetObject("business-logistics-abstract-concept-vector-illustration-smart-logistics-technolog" +
                        "ies-commercial-delivery-service-worldwide-business-transportation-global-product" +
                        "-shipment-abstract-metaphor_335657-1788", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_logistics_abstract_concept_vector_illustration_smart_logistics_technologies_commercial_delivery_service_worldwide_business_transportation_global_product_shipment_abstract_metaphor_335657_17881 {
            get {
                object obj = ResourceManager.GetObject("business-logistics-abstract-concept-vector-illustration-smart-logistics-technolog" +
                        "ies-commercial-delivery-service-worldwide-business-transportation-global-product" +
                        "-shipment-abstract-metaphor_335657-17881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_logistics_abstract_concept_vector_illustration_smart_logistics_technologies_commercial_delivery_service_worldwide_business_transportation_global_product_shipment_abstract_metaphor_335657_17882 {
            get {
                object obj = ResourceManager.GetObject("business-logistics-abstract-concept-vector-illustration-smart-logistics-technolog" +
                        "ies-commercial-delivery-service-worldwide-business-transportation-global-product" +
                        "-shipment-abstract-metaphor_335657-17882", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap businessmen_shaking_hands_through_display_video_call_smart_phone_internet_business_concept_cartoon_character_vector_illustration_1150_56245 {
            get {
                object obj = ResourceManager.GetObject("businessmen-shaking-hands-through-display-video-call-smart-phone-internet-busines" +
                        "s-concept-cartoon-character-vector-illustration_1150-56245", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap businessmen_shaking_hands_through_display_video_call_smart_phone_internet_business_concept_cartoon_character_vector_illustration_1150_562451 {
            get {
                object obj = ResourceManager.GetObject("businessmen-shaking-hands-through-display-video-call-smart-phone-internet-busines" +
                        "s-concept-cartoon-character-vector-illustration_1150-562451", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap businessmen_shaking_hands_through_display_video_call_smart_phone_internet_business_concept_cartoon_character_vector_illustration_1150_562452 {
            get {
                object obj = ResourceManager.GetObject("businessmen-shaking-hands-through-display-video-call-smart-phone-internet-busines" +
                        "s-concept-cartoon-character-vector-illustration_1150-562452", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap character_illustration_home_improvement_concept_53876_43040 {
            get {
                object obj = ResourceManager.GetObject("character-illustration-home-improvement-concept_53876-43040", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap character_illustration_home_improvement_concept_53876_43040__1_ {
            get {
                object obj = ResourceManager.GetObject("character-illustration-home-improvement-concept_53876-43040 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap character_illustration_home_improvement_concept_53876_43040__1_1 {
            get {
                object obj = ResourceManager.GetObject("character-illustration-home-improvement-concept_53876-43040 (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap constructing_tomorrow_glimpse_into_construction_worker_s_life_772298_19025 {
            get {
                object obj = ResourceManager.GetObject("constructing-tomorrow-glimpse-into-construction-worker-s-life_772298-19025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap constructing_tomorrow_glimpse_into_construction_worker_s_life_772298_190251 {
            get {
                object obj = ResourceManager.GetObject("constructing-tomorrow-glimpse-into-construction-worker-s-life_772298-190251", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap construction_worker_with_construction_icons_24877_27249 {
            get {
                object obj = ResourceManager.GetObject("construction-worker-with-construction-icons_24877-27249", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap construction_worker_with_construction_icons_24877_272491 {
            get {
                object obj = ResourceManager.GetObject("construction-worker-with-construction-icons_24877-272491", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap construction_worker_with_construction_icons_24877_272492 {
            get {
                object obj = ResourceManager.GetObject("construction-worker-with-construction-icons_24877-272492", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_issues_icon_3d_illustration_from_customer_relationship_collection_creative_customer_issues_3d_icon_web_design_templates_infographics_more_676904_890 {
            get {
                object obj = ResourceManager.GetObject("customer-issues-icon-3d-illustration-from-customer-relationship-collection-creati" +
                        "ve-customer-issues-3d-icon-web-design-templates-infographics-more_676904-890", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delivery_banner_set_1284_13055 {
            get {
                object obj = ResourceManager.GetObject("delivery-banner-set_1284-13055", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap detailed_image_supply_chain_diagram_emphasizing_use_nearby_suppliers_216520_10778 {
            get {
                object obj = ResourceManager.GetObject("detailed-image-supply-chain-diagram-emphasizing-use-nearby-suppliers_216520-10778" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diagram_supply_chain_management_1308_100127 {
            get {
                object obj = ResourceManager.GetObject("diagram-supply-chain-management_1308-100127", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap different_reactions_with_empty_space_wallpaper_79603_1030 {
            get {
                object obj = ResourceManager.GetObject("different-reactions-with-empty-space-wallpaper_79603-1030", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emotional_design_abstract_concept_illustration_335657_3821 {
            get {
                object obj = ResourceManager.GetObject("emotional-design-abstract-concept-illustration_335657-3821", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engineer_men_group_with_helmet_secure_24877_57279 {
            get {
                object obj = ResourceManager.GetObject("engineer-men-group-with-helmet-secure_24877-57279", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engineer_men_group_with_helmet_secure_24877_572791 {
            get {
                object obj = ResourceManager.GetObject("engineer-men-group-with-helmet-secure_24877-572791", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engineer_men_group_with_helmet_secure_24877_572792 {
            get {
                object obj = ResourceManager.GetObject("engineer-men-group-with-helmet-secure_24877-572792", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engineering_construction_illustration_23_2148891048 {
            get {
                object obj = ResourceManager.GetObject("engineering-construction-illustration_23-2148891048", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engineers_team_discussing_issues_construction_site_74855_4786 {
            get {
                object obj = ResourceManager.GetObject("engineers-team-discussing-issues-construction-site_74855-4786", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engineers_team_discussing_issues_construction_site_74855_47861 {
            get {
                object obj = ResourceManager.GetObject("engineers-team-discussing-issues-construction-site_74855-47861", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engineers_team_discussing_issues_construction_site_74855_47862 {
            get {
                object obj = ResourceManager.GetObject("engineers-team-discussing-issues-construction-site_74855-47862", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engineers_team_discussing_issues_construction_site_74855_47863 {
            get {
                object obj = ResourceManager.GetObject("engineers-team-discussing-issues-construction-site_74855-47863", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fertilizer_production_process_flat_vector_illustration_isolated_white_background_181313_4645 {
            get {
                object obj = ResourceManager.GetObject("fertilizer-production-process-flat-vector-illustration-isolated-white-background_" +
                        "181313-4645", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flat_customer_service_week_illustration_23_2149621449 {
            get {
                object obj = ResourceManager.GetObject("flat-customer-service-week-illustration_23-2149621449", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flat_design_business_people_concept_122818_199 {
            get {
                object obj = ResourceManager.GetObject("flat-design-business-people-concept_122818-199", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flat_design_business_people_concept_122818_1991 {
            get {
                object obj = ResourceManager.GetObject("flat-design-business-people-concept_122818-1991", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hand_drawn_flat_design_international_trade_23_2149180270 {
            get {
                object obj = ResourceManager.GetObject("hand-drawn-flat-design-international-trade_23-2149180270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_background_remover_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-background-remover-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_budget_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-budget-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_budget_planning_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-budget-planning-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_budget_planning_64__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-budget-planning-64 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_circle_chart_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-circle-chart-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cloud_alert_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-cloud-alert-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_delete_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-delete-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_explore_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-explore-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_explore_501 {
            get {
                object obj = ResourceManager.GetObject("icons8-explore-501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_explore_502 {
            get {
                object obj = ResourceManager.GetObject("icons8-explore-502", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_feedback_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-feedback-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_goods_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-goods-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_list_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-list-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_machinery_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-machinery-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_machinery_501 {
            get {
                object obj = ResourceManager.GetObject("icons8-machinery-501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_notepad_user_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-notepad-user-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_notepad_user_50__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-notepad-user-50 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_password_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-password-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_person_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-person-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_role_66 {
            get {
                object obj = ResourceManager.GetObject("icons8-role-66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_search_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-search-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_speed_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-speed-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_speed_501 {
            get {
                object obj = ResourceManager.GetObject("icons8-speed-501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_username_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-username-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_windows_update_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-windows-update-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap illustration_with_multitasking_concept_23_2148408832 {
            get {
                object obj = ResourceManager.GetObject("illustration-with-multitasking-concept_23-2148408832", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap industrial_abstract_machine_flat_style_factory_construction_equipment_engineering_1284_42835 {
            get {
                object obj = ResourceManager.GetObject("industrial-abstract-machine-flat-style-factory-construction-equipment-engineering" +
                        "_1284-42835", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap industrial_engineering_elements_set_flat_style_1284_47530 {
            get {
                object obj = ResourceManager.GetObject("industrial-engineering-elements-set-flat-style_1284-47530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_concept_illustration_114360_739 {
            get {
                object obj = ResourceManager.GetObject("login-concept-illustration_114360-739", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logistics_business_flat_concept_warehouse_worker_delivery_man_goods_crate_movement_process_126523_2207 {
            get {
                object obj = ResourceManager.GetObject("logistics-business-flat-concept-warehouse-worker-delivery-man-goods-crate-movemen" +
                        "t-process_126523-2207", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_community_24877_51947 {
            get {
                object obj = ResourceManager.GetObject("online-community_24877-51947", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_community_24877_519471 {
            get {
                object obj = ResourceManager.GetObject("online-community_24877-519471", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap processing_concept_illustration_114360_410 {
            get {
                object obj = ResourceManager.GetObject("processing-concept-illustration_114360-410", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap processing_concept_illustration_114360_4101 {
            get {
                object obj = ResourceManager.GetObject("processing-concept-illustration_114360-4101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap processing_concept_illustration_114360_4102 {
            get {
                object obj = ResourceManager.GetObject("processing-concept-illustration_114360-4102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap processing_concept_illustration_114360_4103 {
            get {
                object obj = ResourceManager.GetObject("processing-concept-illustration_114360-4103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product_quality_concept_illustration_114360_7461 {
            get {
                object obj = ResourceManager.GetObject("product-quality-concept-illustration_114360-7461", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap professional_conditioning_services_repairs_regular_maintenance_flat_vector_illustration_banner_air_conditioner_repair_engineering_services_banner_template_605858_2305 {
            get {
                object obj = ResourceManager.GetObject("professional-conditioning-services-repairs-regular-maintenance-flat-vector-illust" +
                        "ration-banner-air-conditioner-repair-engineering-services-banner-template_605858" +
                        "-2305", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap real_estate_development_set_74855_2479 {
            get {
                object obj = ResourceManager.GetObject("real-estate-development-set_74855-2479", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap risk_management_concept_illustration_114360_6957 {
            get {
                object obj = ResourceManager.GetObject("risk-management-concept-illustration_114360-6957", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap risk_management_concept_illustration_114360_69571 {
            get {
                object obj = ResourceManager.GetObject("risk-management-concept-illustration_114360-69571", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap satisfaction_loyalty_customer_care_rating_site_concept_269730_792 {
            get {
                object obj = ResourceManager.GetObject("satisfaction-loyalty-customer-care-rating-site-concept_269730-792", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap satisfaction_loyalty_customer_care_rating_site_concept_269730_7921 {
            get {
                object obj = ResourceManager.GetObject("satisfaction-loyalty-customer-care-rating-site-concept_269730-7921", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_04_17_173611 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-04-17 173611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_04_17_173650 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-04-17 173650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_04_19_001928 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-04-19 001928", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shot_group_workers_conducting_mock_production_line_demonstrating_their_crossfunctional_216520_12641 {
            get {
                object obj = ResourceManager.GetObject("shot-group-workers-conducting-mock-production-line-demonstrating-their-crossfunct" +
                        "ional_216520-12641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap three_engineers_standing_construction_site_74855_4658 {
            get {
                object obj = ResourceManager.GetObject("three-engineers-standing-construction-site_74855-4658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warehouse_composition_1284_25348 {
            get {
                object obj = ResourceManager.GetObject("warehouse-composition_1284-25348", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning_concept_illustration_114360_1551 {
            get {
                object obj = ResourceManager.GetObject("warning-concept-illustration_114360-1551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap website_maintenance_abstract_concept_vector_illustration_website_service_webpage_seo_maintenance_web_design_corporate_site_professional_support_security_analysis_update_abstract_metaphor_335657_2295 {
            get {
                object obj = ResourceManager.GetObject("website-maintenance-abstract-concept-vector-illustration-website-service-webpage-" +
                        "seo-maintenance-web-design-corporate-site-professional-support-security-analysis" +
                        "-update-abstract-metaphor_335657-2295", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap women_with_computer_ecommerce_technology_sale_24877_56059 {
            get {
                object obj = ResourceManager.GetObject("women-with-computer-ecommerce-technology-sale_24877-56059", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
